# Generated by Django 6.0 on 2025-12-21 10:20

import autoslug.fields
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Название компании')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО продавца')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='company_name_or_name', unique=True, verbose_name='URL')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание продавца')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Проверен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
            },
        ),
    ]
